import { Router } from "express";
import { pool, one } from "../db.js";
import { requireAuth, requireRole } from "../auth.js";
import { notify, coordinatorIds } from "../notify.js";
import { isOps, managerRestaurantIds } from "../access.js";
import { monthRefOf } from "../payroll.js";

// Manager feedback (§10). Manager submits 1–5★ + mandatory justification
// (pending_validation); coordinator categorizes (§10.2) and validates, which
// posts the category's points to the freelancer's score. 40% coverage (§10.3)
// is generated by the scheduler (see generateFeedbackRequests).
const router = Router();
router.use(requireAuth);
const requireOps = requireRole("coordinator", "administrator");

// §10.2 categories → fixed points and the matching score event type.
const FEEDBACK_POINTS = { fundamentos: 1, proatividade: 2, encantamento: 3, extraordinario: 5 };
const CATEGORY_EVENT = {
  fundamentos: "feedback_fundamentos", proatividade: "feedback_proatividade",
  encantamento: "feedback_encantamento", extraordinario: "feedback_extraordinario",
};

const FB_SELECT = `
  f.id, f.restaurant_id as "restaurantId", f.manager_user_id as "managerUserId",
  f.freelancer_user_id as "freelancerUserId", f.assignment_id as "assignmentId",
  f.stars, f.justification, f.status, f.category,
  f.points_awarded as "pointsAwarded", f.validated_at as "validatedAt",
  f.created_at as "createdAt",
  r.name as "restaurantName", mgr.name as "managerName", fl.name as "freelancerName"`;
const FB_FROM = `
  from public.manager_feedback f
  left join public.restaurants r on r.id = f.restaurant_id
  left join public.users mgr on mgr.id = f.manager_user_id
  left join public.users fl on fl.id = f.freelancer_user_id`;

async function recomputeScore(userId) {
  await pool.query(
    `update public.freelancer_profiles
       set current_score = coalesce(
         (select sum(points) from public.score_events where user_id = $1 and is_voided = false), 0)
     where user_id = $1`,
    [userId],
  );
}

// ---------------------------------------------------------------------------
// GET /api/feedback — role-scoped.
//   manager → { toGive, submitted }
//   coordinator/admin → { queue, recent }
// ---------------------------------------------------------------------------
router.get("/", async (req, res) => {
  try {
    if (isOps(req.user.role)) {
      const { rows: queue } = await pool.query(
        `select ${FB_SELECT} ${FB_FROM} where f.status = 'pending_validation'
          order by f.created_at asc`,
      );
      const { rows: recent } = await pool.query(
        `select ${FB_SELECT} ${FB_FROM} where f.status in ('validated','rejected')
          order by f.validated_at desc nulls last, f.created_at desc limit 30`,
      );
      return res.json({ queue, recent });
    }
    if (req.user.role === "restaurant_manager") {
      const me = req.user.sub;
      const { rows: toGive } = await pool.query(
        `select fr.id, fr.restaurant_id as "restaurantId", fr.freelancer_user_id as "freelancerUserId",
                fr.assignment_id as "assignmentId", fr.month_ref::text as "monthRef",
                r.name as "restaurantName", fl.name as "freelancerName",
                a.date::text as date, a.shift_type as "shiftType"
           from public.feedback_requests fr
           left join public.restaurants r on r.id = fr.restaurant_id
           left join public.users fl on fl.id = fr.freelancer_user_id
           left join public.schedule_assignments a on a.id = fr.assignment_id
          where fr.manager_user_id = $1 and fr.status = 'pending'
          order by fr.created_at asc`,
        [me],
      );
      const { rows: submitted } = await pool.query(
        `select ${FB_SELECT} ${FB_FROM} where f.manager_user_id = $1
          order by f.created_at desc limit 50`,
        [me],
      );
      return res.json({ toGive, submitted });
    }
    res.status(403).json({ error: "Forbidden" });
  } catch (e) {
    console.error("feedback list error:", e.message);
    res.status(500).json({ error: "Falha ao carregar feedbacks." });
  }
});

// GET /api/feedback/candidates — freelancers a manager may rate (scheduled at
// their restaurant(s)). Lets managers give ad-hoc feedback beyond the 40% requests.
router.get("/candidates", async (req, res) => {
  try {
    if (req.user.role !== "restaurant_manager" && !isOps(req.user.role)) {
      return res.status(403).json({ error: "Forbidden" });
    }
    const rids = isOps(req.user.role) ? null : await managerRestaurantIds(req.user.sub);
    if (rids && rids.length === 0) return res.json([]);
    const params = [];
    let restWhere = "";
    if (rids) { params.push(rids); restWhere = `and a.restaurant_id = any($1)`; }
    const { rows } = await pool.query(
      `select distinct a.restaurant_id as "restaurantId", r.name as "restaurantName",
              u.id as "freelancerUserId", u.name as "freelancerName"
         from public.schedule_assignments a
         join public.users u on u.id = a.user_id
         left join public.restaurants r on r.id = a.restaurant_id
        where a.status = 'published' ${restWhere}
        order by r.name asc, u.name asc`,
      params,
    );
    res.json(rows);
  } catch (e) {
    console.error("feedback candidates error:", e.message);
    res.status(500).json({ error: "Falha ao carregar candidatos." });
  }
});

// POST /api/feedback { restaurantId, freelancerUserId, stars, justification, assignmentId?, requestId? }
router.post("/", async (req, res) => {
  try {
    const b = req.body || {};
    const ops = isOps(req.user.role);
    if (req.user.role !== "restaurant_manager" && !ops) {
      return res.status(403).json({ error: "Forbidden" });
    }
    if (!b.restaurantId || !b.freelancerUserId) {
      return res.status(400).json({ error: "restaurantId and freelancerUserId are required" });
    }
    const stars = Number(b.stars);
    if (!Number.isInteger(stars) || stars < 1 || stars > 5) {
      return res.status(400).json({ error: "invalid_stars", message: "Dê uma nota de 1 a 5 estrelas." });
    }
    if (!b.justification || !String(b.justification).trim()) {
      return res.status(400).json({ error: "justification_required", message: "A justificativa é obrigatória." });
    }
    // A manager may only rate their own restaurant(s).
    if (!ops) {
      const rids = await managerRestaurantIds(req.user.sub);
      if (!rids.includes(b.restaurantId)) {
        return res.status(403).json({ error: "forbidden_restaurant", message: "Você só pode avaliar no seu restaurante." });
      }
    }

    const row = await one(
      `insert into public.manager_feedback
         (restaurant_id, manager_user_id, freelancer_user_id, assignment_id, stars, justification, status)
       values ($1,$2,$3,$4,$5,$6,'pending_validation') returning id`,
      [b.restaurantId, req.user.sub, b.freelancerUserId, b.assignmentId ?? null, stars, String(b.justification).trim()],
    );

    // Mark the originating 40% request completed, if any.
    if (b.requestId) {
      await pool.query(`update public.feedback_requests set status='completed' where id=$1 and manager_user_id=$2`,
        [b.requestId, req.user.sub]);
    }

    for (const cid of await coordinatorIds()) {
      await notify({ recipientUserId: cid, type: "feedback_received",
        title: "Novo feedback de gestor",
        body: "Um gestor enviou um feedback. Valide e categorize para pontuar.",
        data: { feedbackId: row.id } });
    }
    res.status(201).json({ id: row.id, status: "pending_validation" });
  } catch (e) {
    console.error("feedback create error:", e.message);
    res.status(500).json({ error: "Falha ao enviar feedback." });
  }
});

// POST /api/feedback/:id/validate { category } — coordinator categorizes + scores (§10.2).
router.post("/:id/validate", requireOps, async (req, res) => {
  try {
    const category = (req.body || {}).category;
    if (!category || !(category in FEEDBACK_POINTS)) {
      return res.status(400).json({ error: "invalid_category", message: "Categoria inválida." });
    }
    const f = await one(
      `select id, freelancer_user_id as "freelancerUserId", status, created_at::text as "createdAt"
         from public.manager_feedback where id = $1`,
      [req.params.id],
    );
    if (!f) return res.status(404).json({ error: "Not found" });
    if (f.status !== "pending_validation") {
      return res.status(400).json({ error: "bad_state", message: "Este feedback já foi avaliado." });
    }
    const points = FEEDBACK_POINTS[category];
    const occurredOn = f.createdAt.slice(0, 10);

    const ev = await one(
      `insert into public.score_events
         (user_id, event_type, points, reference_type, reference_id, occurred_on, month_ref, created_by, notes)
       values ($1,$2,$3,'feedback',$4,$5,$6,$7,$8) returning id`,
      [f.freelancerUserId, CATEGORY_EVENT[category], points, f.id, occurredOn,
        monthRefOf(occurredOn), req.user.sub, `feedback ${category}`],
    );
    await pool.query(
      `update public.manager_feedback
          set status='validated', category=$2, points_awarded=$3,
              validated_by=$4, validated_at=now(), score_event_id=$5
        where id=$1`,
      [f.id, category, points, req.user.sub, ev.id],
    );
    await recomputeScore(f.freelancerUserId);
    res.json({ status: "validated", category, pointsAwarded: points });
  } catch (e) {
    console.error("feedback validate error:", e.message);
    res.status(500).json({ error: "Falha ao validar." });
  }
});

// POST /api/feedback/:id/reject — coordinator rejects (no score).
router.post("/:id/reject", requireOps, async (req, res) => {
  try {
    const f = await one(`select id, status from public.manager_feedback where id=$1`, [req.params.id]);
    if (!f) return res.status(404).json({ error: "Not found" });
    if (f.status !== "pending_validation") {
      return res.status(400).json({ error: "bad_state", message: "Este feedback já foi avaliado." });
    }
    await pool.query(
      `update public.manager_feedback set status='rejected', validated_by=$2, validated_at=now() where id=$1`,
      [f.id, req.user.sub],
    );
    res.json({ status: "rejected" });
  } catch (e) {
    console.error("feedback reject error:", e.message);
    res.status(500).json({ error: "Falha ao recusar." });
  }
});

// GET /api/feedback/coverage?month=YYYY-MM — coordinator: 40% progress per freelancer (§10.3).
router.get("/coverage", requireOps, async (req, res) => {
  try {
    const month = String(req.query.month || new Date().toISOString().slice(0, 7));
    const monthRef = `${month.slice(0, 7)}-01`;
    const pctRow = await one(`select feedback_coverage_pct as pct from public.app_settings where id=1`);
    const pct = Number(pctRow?.pct ?? 0.4);
    const { rows } = await pool.query(
      `with shifts as (
         select user_id, count(*)::int as n
           from public.schedule_assignments
          where status='published' and date >= $1::date and date < ($1::date + interval '1 month')
          group by user_id),
       received as (
         select freelancer_user_id as user_id, count(*)::int as n
           from public.manager_feedback
          where status='validated' and created_at >= $1::date and created_at < ($1::date + interval '1 month')
          group by freelancer_user_id)
       select u.id as "userId", u.name,
              coalesce(s.n,0) as shifts, coalesce(rc.n,0) as received
         from shifts s
         join public.users u on u.id = s.user_id
         left join received rc on rc.user_id = s.user_id
        order by u.name asc`,
      [monthRef],
    );
    res.json(rows.map((r) => ({
      userId: r.userId, name: r.name, shifts: Number(r.shifts),
      received: Number(r.received), target: Math.ceil(Number(r.shifts) * pct),
    })));
  } catch (e) {
    console.error("feedback coverage error:", e.message);
    res.status(500).json({ error: "Falha ao carregar cobertura." });
  }
});

export default router;
